version: '3.1'
services:
  web:
    build: .
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    command: bash -c "yarn start"
    volumes:
      - .:/cashregister_frontend
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"